### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by DylanJi** [AudioNet/node-core-audio#77]
When I install this package, the error information as follows:
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
66:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Electron\TestPrj\node_modules\node-core-audio
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN testp@1.0.0 No description
npm WARN testp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-core-audio@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-core-audio@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

so, how can i save this problem? thanks

**Comment by Mondonno** [comment]
I have this too! Please help!

**Comment by kemphack** [comment]
Check out my version of this lib, its working for newer versions https://github.com/kemphack/node-core-audio

**Comment by vidicunt** [comment]
> Check out my version of this lib, its working for newer versions https://github.com/kemphack/node-core-audio

do you have a npm package?
